trigger:
- main

pool:
  name: Default

steps:
- task: UseNode@1
  displayName: 'Usar Node.js 16'
  inputs:
    version: '16.x'

- script: |
    npm ci
  displayName: 'Instalar dependencias'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    npm run build
  displayName: 'Compilar frontend Vue'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    chmod +x ./mvnw
    ./mvnw -f grocery-backend/pom.xml clean package -DskipTests
  displayName: 'Compilar backend Spring Boot'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: AzureStaticWebApp@0
  displayName: 'Desplegar frontend a Azure Static Web App'
  inputs:
    app_location: '/'
    output_location: 'dist'
    skip_app_build: true
    azure_static_web_apps_api_token: '$(853940fc8b252a771db3623a597ee6988e18579dd818361250d17d0284ba5d9a07-a30caedf-07c0-4be6-acb1-b5ecc4c32fb701e1721088b02b1e)'