trigger:
- main

pool:
  name: Default

steps:
- task: UseNode@1
  displayName: 'Usar Node.js 16'
  inputs:
    version: '16.x'

- script: |
    npm ci
  displayName: 'Instalar dependencias'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    npm run build
  displayName: 'Compilar frontend Vue'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH
    chmod +x ./mvnw
    ./mvnw -f grocery-backend/pom.xml clean package -DskipTests
  displayName: 'Compilar backend Spring Boot'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: AzureStaticWebApp@0
  displayName: 'Desplegar frontend a Azure Static Web App'
  inputs:
    app_location: '/dist'
    output_location: ''
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'